[package]
name = "event-autopin-desktop"
version = "0.1.13"
edition = "2021"

[build-dependencies]
tauri-build = { version = "1.5", features = [] }

[dependencies]
serde_json = "1"
serde = { version = "1", features = ["derive"] }
tauri = { version = "1.6", features = [ "window-close", "dialog-ask", "dialog-message", "protocol-asset", "shell-open", "dialog-open", "devtools", "process-exit"] }
tokio = { version = "1", features = ["rt"] }
reqwest = { version = "0.11", features = ["blocking", "json"] }
tiny_http = "0.12"
local-ip-address = "0.6"
zip = "0.6"
chrono = "0.4"
unicode-normalization = "0.1"
windows-sys = { version = "0.61", features = ["Win32_Foundation", "Win32_Security", "Win32_Security_Authorization", "Win32_Storage_FileSystem", "Win32_System_JobObjects", "Win32_System_Threading", "Win32_UI_WindowsAndMessaging"] }

[features]
default = ["custom-protocol"]
custom-protocol = ["tauri/custom-protocol"]
